### ISSUE TITLE
Toogle for SSH Keys

### ISSUE THREAD

**Issue by olemyk** [acch/ansible-scale#2]
Future improvement is to have a toggle for SSH Key Exchange between nodes, this is for customers that have this already in place.   "prepare | Read public SSH key"  " prepare | Authorize all SSH keys"

**Comment by acch** [comment]
I've added the following option - please let me know if this suffices the requirement:
```
defaults/main.yml:
...
## Whether or not to exchange SSH keys between nodes
scale_prepare_exchange_keys: true
...
```
