### ISSUE TITLE
Use a repo even for localpkg install

### ISSUE THREAD

**Issue by mattiasb** [acch/ansible-scale#6]
When performing a `localpkg` install you could probably simplify the installation logic a bit by setting `scale_install_repository_url` to a `file:`-url since yum can handle that and since the installation script contains a `repodata` directory. 

Something like this:
```yaml
scale_install_repository_url: file:///usr/lpp/mmfs/{{ scale_version }}/gpfs_rpms/
```

I tried this for the `ansible-scale-gui` role and that worked fine. :)

**Comment by acch** [comment]
The `localpkg` installation method takes a self-extracting installation package (the thing you download from FixCentral), while the `repository` installation method expects that package to be extracted somewhere and takes the resulting RPM files and repo metadata:

```
## Specify the URL of the (existing) Spectrum Scale YUM repository
## (copy the contents of /usr/lpp/mmfs/.../gpfs_rpms to build your repository)
```

I don't see the use case for manually extracting the installation package on every node and then using the `repository` installation method to point it to local files... what's the benefit? `localpkg` installation method will take care of copying it over and extracting it, `remotepkg` will skip the copy but perform the extract.

**Comment by mattiasb** [comment]
@acch For the end user the benefit is none. :) For you, developing the role, you might be able to shave some lines of code, reusing what you already have in the `install_repository.yml` file. So the `install_localpkg.yml` would only need to run the unpackaging stuff and then install from the locally hosted repository you already have code fore.

Re: extracting the installation package in every node I don't have a good answer. It indeed seems better to set up a repository once and then using that. But this was more about reducing lines of code and hence your test matrix.

**Comment by mattiasb** [comment]
TBH I don't fully understand the difference between `install_localpkg.yml` and `install_remotepkg.yml`, I'd have to study the code more closely for that.

**Comment by acch** [comment]
Have you found a use case for using the `repository` installation method to point to local files? Otherwise I'd suggest to close this issue - do you agree?

**Comment by mattiasb** [comment]
Close! :)
